spring.application.name=Quzby_shop

project.image =images/

spring.jpa.show-sql =true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.hibernate.ddl-auto = update

spring.datasource.url=jdbc:mysql://mysql:3306/quzby_db
spring.datasource.username=root
spring.datasource.password=root
